pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "Terraform"
    }
    parameters {
        string(name: 'Workspace', defaultValue: 'development', description:'setting up workspace for terraform')
    }
    environment {
        TF_HOME = tool('Terraform')
        TP_LOG = "WARN"
        PATH = "$TF_HOME:$PATH"
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                script {
                    dir('jenkins-terraform-pipeline/jenkins_pipeline/') {
                        git 'https://github.com/ExePtion31/Terraform-Jenkins'
                    }
                }
            }
        }
        stage('Terraform Init') {
            steps {
                dir('jenkins-terraform-pipeline/jenkins_pipeline/'){
                    bat "terraform init -input=false"
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('jenkins-terraform-pipeline/jenkins_pipeline/'){
                    bat "terraform apply -auto-approve"
                }
            }
        }
    }
}